<?php

return [
    'name' => '1. ICAHN MEMORIAL',
    'tagline' => 'Where the night runs brighter.',
    'date' => '18 JULY 2027',
    'venue' => 'Icahn Athletics Stadium',
    'location' => 'New York City · International Meeting',
    'email' => 'hello@icahnmemorial.test',
    'phone' => '+00 000 000 000',
    'hero' => 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=2200&q=85',
    'images' => [
        'track' => 'https://images.unsplash.com/photo-1530137073520-26d14c8c5f72?auto=format&fit=crop&w=1400&q=80',
        'field' => 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1400&q=80',
        'crowd' => 'https://images.unsplash.com/photo-1502904550040-7534597429ae?auto=format&fit=crop&w=1400&q=80',
    ],
    'athletes' => [
        ['name' => 'Carl Lewis', 'country' => 'United States', 'discipline' => 'Sprints / Long Jump', 'highlight' => 'Nine-time Olympic gold medalist', 'image' => 'images/icahn-athlete-carl-lewis.png'],
        ['name' => 'Florence Griffith Joyner (Flo-Jo)', 'country' => 'United States', 'discipline' => 'Sprints', 'highlight' => 'Women’s 100m and 200m world record holder', 'image' => 'images/icahn-athlete-flo-jo.png'],
        ['name' => 'Jim Beatty', 'country' => 'United States', 'discipline' => 'Middle-distance running', 'highlight' => 'First person to run a sub-four-minute indoor mile in 1962', 'image' => 'images/icahn-athlete-jim-beatty.png'],
    ],
    'news' => [
        ['slug' => 'the-night-session-takes-shape', 'date' => '06.03.2027', 'category' => 'Meeting update', 'title' => 'The night session takes shape', 'excerpt' => 'A first look at the pace, precision and atmosphere being built for the Icahn Memorial.', 'image' => 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1000&q=80'],
        ['slug' => 'a-new-stage-for-field-events', 'date' => '21.02.2027', 'category' => 'Venue', 'title' => 'A new stage for field events', 'excerpt' => 'The infield is designed so every take-off, throw and landing can be felt from the stands.', 'image' => 'https://images.unsplash.com/photo-1593113646773-028c64a8f1b8?auto=format&fit=crop&w=1000&q=80'],
        ['slug' => 'volunteers-open-the-gates', 'date' => '10.02.2027', 'category' => 'Community', 'title' => 'Volunteers open the gates', 'excerpt' => 'Meet the team that will turn an ordinary July evening into a shared occasion.', 'image' => 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&w=1000&q=80'],
    ],
    'schedules' => [
        'amateur' => [
            ['time'=>'14:00','event'=>'Open 5000m','class'=>'2 heats'],
            ['time'=>'14:45','event'=>'Open mile','class'=>'3 heats'],
            ['time'=>'15:35','event'=>'Open 400m','class'=>'3 heats'],
            ['time'=>'16:20','event'=>'100m','class'=>'Amateur'],
            ['time'=>'16:35','event'=>'200m','class'=>'Amateur'],
            ['time'=>'16:55','event'=>'800m','class'=>'Amateur'],
            ['time'=>'17:20','event'=>'Mile','class'=>'Amateur'],
            ['time'=>'17:45','event'=>'5000m','class'=>'Amateur'],
            ['time'=>'18:20','event'=>'3000m steeplechase','class'=>'Amateur'],
        ],
        'elite' => [
            ['time'=>'18:30','event'=>'Women’s pole vault','class'=>'Elite'],
            ['time'=>'18:45','event'=>'Women’s long jump','class'=>'Elite'],
            ['time'=>'19:00','event'=>'Women’s discus throw','class'=>'Elite'],
            ['time'=>'19:15','event'=>'Women’s 800m','class'=>'Elite'],
            ['time'=>'19:30','event'=>'Women’s 100m','class'=>'Elite'],
            ['time'=>'19:45','event'=>'Women’s 10,000m','class'=>'Elite'],
            ['time'=>'20:10','event'=>'Women’s 400m hurdles','class'=>'Elite'],
            ['time'=>'20:25','event'=>'Men’s shot put','class'=>'Elite'],
            ['time'=>'20:35','event'=>'Men’s discus throw','class'=>'Elite'],
            ['time'=>'20:45','event'=>'Men’s high jump','class'=>'Elite'],
            ['time'=>'21:00','event'=>'Men’s 1500m','class'=>'Elite'],
            ['time'=>'21:15','event'=>'Men’s 3000m','class'=>'Elite'],
            ['time'=>'21:30','event'=>'Men’s 800m','class'=>'Elite'],
            ['time'=>'21:45','event'=>'Men’s 400m hurdles','class'=>'Elite'],
        ],
    ],
];
